## CASE STUDEY: Olympic 2012 Medal Tally

In [3]:
import pandas as pd
import numpy as np

In [4]:
dataframe = pd.read_excel('Olympic 2012 Medal Tally.xlsx', names=['column1', 'Country', 'Country_Code', 'year','Gold','Silver','Bronze'],skiprows=2)

In [5]:
dataframe

column1        Country Country_Code  year  Gold  Silver  Bronze
0      NaN  Great Britain          GBR  2012    29      17      19
1      NaN         China           CHN  2012    38      28      22
2      NaN         Russia          RUS  2012    24      25      32
3      NaN  United States           US  2012    46      28      29
4      NaN          Korea          KOR  2012    13       8       7
5      NaN          Japan          JPN  2012     7      14      17
6      NaN        Germany          GER  2012    11      11      14

In [6]:
country_name = np.array(dataframe['Country'].values)

In [7]:
country_name

array(['Great Britain', 'China ', 'Russia', 'United States', 'Korea',
       'Japan', 'Germany'], dtype=object)

In [8]:
gold = np.array(dataframe['Gold'].values)

In [9]:
gold

array([29, 38, 24, 46, 13,  7, 11], dtype=int64)

In [10]:
silver = np.array(dataframe['Silver'].values)

In [11]:
silver

array([17, 28, 25, 28,  8, 14, 11], dtype=int64)

In [12]:
bronze = np.array(dataframe['Bronze'].values)

In [13]:
bronze

array([19, 22, 32, 29,  7, 17, 14], dtype=int64)

### 1. Find and print the name of the country that won maximum gold medals.

In [14]:
max_gold_medal = gold.argmax()

In [15]:
country_name_won_max_gold_medal = country_name[max_gold_medal]

In [16]:
country_name_won_max_gold_medal

'United States'

### 2. Find and print the countries who won more than 20 gold medals.

In [17]:
gold_medal_won_morethan20 = gold>20

In [18]:
country_name_gold_medal_won_morethan20 = country_name[gold_medal_won_morethan20]

In [19]:
print(country_name_gold_medal_won_morethan20)

['Great Britain' 'China ' 'Russia' 'United States']


### 3. Print each country name with the corresponding number of gold medals.

In [20]:
for counter in range(len(country_name)):
    print("--> {} won {} Gold Medals.".format(country_name[counter], gold[counter]))

--> Great Britain won 29 Gold Medals.
--> China  won 38 Gold Medals.
--> Russia won 24 Gold Medals.
--> United States won 46 Gold Medals.
--> Korea won 13 Gold Medals.
--> Japan won 7 Gold Medals.
--> Germany won 11 Gold Medals.


### 4. Print each country name with the total number of medals won.

In [22]:
for counter in range(len(country_name)):
    print("--> {} won total {} medals.".format(country_name[counter], (gold[counter]+silver[counter]+bronze[counter])))

--> Great Britain won total 65 medals.
--> China  won total 88 medals.
--> Russia won total 81 medals.
--> United States won total 103 medals.
--> Korea won total 28 medals.
--> Japan won total 38 medals.
--> Germany won total 36 medals.
